### ISSUE TITLE
Rich ERE to Brat converter offsets problem

### ISSUE THREAD

**Issue by tbmihailov** [hunterhector/EvmEval#14]
I try to convert the LDC2016E71_TAC_KBP_2016_Eval_Core_Set_Rich_ERE_Annotation ERE data to brat.
I use:
java -jar bin/rich_ere_to_brat_converter.jar -t "$ldc_text_dir" -te "xml" -a "$ldc_nugget_dir" -ae "rich_ere.xml" -o "$brat_output_dir" 

It generates warnings for all files:
[WARN] Invalid offset 1961, 1969 of event mention [ police ] for string [displace] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 1988, 1996 of event mention [to displ] for string [showered] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2163, 2169 of event mention [ 1 a.m] for string [firing] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2252, 2260 of event mention [owds of ] for string [gathered] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2252, 2260 of event mention [owds of ] for string [gathered] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2388, 2395 of event mention [ple wer] for string [clashes] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2397, 2409 of event mention [injured in t] for string [according to] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2557, 2564 of event mention [elled g] for string [killing] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2582, 2590 of event mention [a bus, k] for string [injuring] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2582, 2590 of event mention [a bus, k] for string [injuring] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2943, 2951 of event mention [et with ] for string [reported] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 2612, 2620 of event mention [d injuri] for string [reported] at doc [NYT_ENG_20130716.0108]
[WARN] Invalid offset 3100, 3103 of event mention [con] for string [aid] at doc [NYT_ENG_20130716.0108]

It seems that it is a validation offset problem as it compares text with offset -30 with the actual annotation. In the actual ERE everything seems okay.

As it is just a warning I would expect that it will output something but it generates empty output.

**Comment by hunterhector** [comment]
I just run it with the following command and it seems to work fine for me:

`java -jar bin/rich_ere_to_brat_converter.jar -t LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/source -te xml -a LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/ere/ -ae rich_ere.xml -o output
`

The warning appears when the converter cannot match the specified span with the actual mention string, in such case, that mention will be considered as invalid and not output. If all mentions are invalid, the output file might be empty.

It seems to me that you are using a different source or annotation directory.

**Comment by hunterhector** [comment]
Oh, I just realize you are using:

LDC2016E71: TAC KBP 2016 Eval Core Set Rich ERE Annotation 

which is for the Belief task.

But the nugget corpus is actually: 

LDC2016E72: TAC KBP 2016 Eval Core Set Event Nugget Annotation

**Comment by tbmihailov** [comment]
Good point about the datasets. But now tried with LDC2016E72. Same result. I use the last version checked out from github.

**Comment by hunterhector** [comment]
That's weird, I just run it and the output seems to be fine, can you show me the exact command, without bash variables? And a couple examples of warning?

I used exactly the following command and the result looks good:

`java -jar bin/rich_ere_to_brat_converter.jar -t LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/source -te xml -a LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/ere/ -ae rich_ere.xml -o output
`

**Comment by tbmihailov** [comment]
Here is the command:

`java -jar bin/rich_ere_to_brat_converter.jar -t ../tac2016-kbp-event-nuggets/data/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/source -te xml -a ../tac2016-kbp-event-nuggets/data/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/ere -ae rich_ere.xml -o ../tac2016-kbp-event-nuggets/data/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/LDC2016E72_TAC_KBP_2016_Eval_Core_Set_Event_Nugget_Annotation/data/eng/nw/bratNuggetAnn
`

The warning output:
[WARN] Invalid offset 590, 598 of event mention [, accord] for string [released] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 784, 788 of event mention [m by] for string [said] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1240, 1247 of event mention [, affec] for string [sending] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1308, 1314 of event mention [irator] for string [deaths] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1403, 1406 of event mention [cho] for string [hit] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1522, 1528 of event mention [nday.
] for string [killed] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1637, 1644 of event mention [ning. E] for string [injured] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1830, 1836 of event mention [rs spo] for string [called] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 1949, 1956 of event mention [n many ] for string [advised] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 2176, 2186 of event mention [s and susp] for string [production] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 2472, 2477 of event mention [licen] for string [drive] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 2517, 2522 of event mention [d odd] for string [drive] at doc [ENG_NW_001278_20130115_F00013C4Y]
[WARN] Invalid offset 2733, 2737 of event mention [onme] for string [said] at doc [ENG_NW_001278_20130115_F00013C4Y]

**Comment by hunterhector** [comment]
I don't quite understand what is happening here, the text offset seem to be off by 24, which is mysterious to me. Maybe we should verify the file content? I've listed the checksum for the converter and a couple of source xml files down here, can you verify that?

c4d5167c81dfb358dbedac46b28d987f  bin/rich_ere_to_brat_converter.jar

1c99e07ae0c54b87cb915852f4854629  ENG_NW_001278_20130115_F00013C4Y.xml
eee8549e120f57f4346f7a4bf4008f6b  ENG_NW_001278_20130118_F00013MGE.xml
ab4ba582eb6bcdb2a23051188552c8bd  ENG_NW_001278_20130226_F000135NO.xml
4d782dff89974af033a1feb284e79093  ENG_NW_001278_20130304_F00011MYY.xml
96bf0c18f660f4180fe916fb4155e0e6  ENG_NW_001278_20130316_F00011XE2.xml
31992e5e7307ab12dbbaa150e3859da9  ENG_NW_001278_20130316_F000120R5.xml
58ebb6b1531d05f49961451704632edd  ENG_NW_001278_20130316_F00012HSR.xml
d9e32b69381c1412788664df8666d404  ENG_NW_001278_20130319_F00011N3Z.xml
c3122189572fca447096d120e593ab21  ENG_NW_001278_20130324_F00013N20.xml
0f0774d97767942bf70e7054bcfdb88a  ENG_NW_001278_20130327_F00012LCF.xml
43fb639d1c76bc077e1ab40cc0d7cc61  ENG_NW_001278_20130424_F00011JZI.xml

**Comment by tbmihailov** [comment]
Okay, this is weird..

My files are the same:

> c4d5167c81dfb358dbedac46b28d987f  bin/rich_ere_to_brat_converter.jar
> 
> 1c99e07ae0c54b87cb915852f4854629  ENG_NW_001278_20130115_F00013C4Y.xml
> eee8549e120f57f4346f7a4bf4008f6b  ENG_NW_001278_20130118_F00013MGE.xml
> ab4ba582eb6bcdb2a23051188552c8bd  ENG_NW_001278_20130226_F000135NO.xml
> 4d782dff89974af033a1feb284e79093  ENG_NW_001278_20130304_F00011MYY.xml
> 96bf0c18f660f4180fe916fb4155e0e6  ENG_NW_001278_20130316_F00011XE2.xml
> 31992e5e7307ab12dbbaa150e3859da9  ENG_NW_001278_20130316_F000120R5.xml
> 58ebb6b1531d05f49961451704632edd  ENG_NW_001278_20130316_F00012HSR.xml
> d9e32b69381c1412788664df8666d404  ENG_NW_001278_20130319_F00011N3Z.xml
> c3122189572fca447096d120e593ab21  ENG_NW_001278_20130324_F00013N20.xml
> 0f0774d97767942bf70e7054bcfdb88a  ENG_NW_001278_20130327_F00012LCF.xml
> 43fb639d1c76bc077e1ab40cc0d7cc61  ENG_NW_001278_20130424_F00011JZI.xml

OS:

> Operating System: Debian GNU/Linux 8 (jessie)
> Kernel: Linux 3.16.0-4-amd64
> Architecture: x86-64

Here is my java version:

> java version "1.8.0_101"
> Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by hunterhector** [comment]
You probably should email me directly at hunterhector@gmail.com, I may be able to arrange provide you the Brat standalone annotations (the .ann files), and you need to just need to rename the .xml files into .txt, and put them all in the same directory.

**Comment by tbmihailov** [comment]
Tried the conversion on a machine with Ubuntu and it works without any issues.

> Distributor ID:   Ubuntu
> Description:  Ubuntu 16.04.1 LTS
> Release:  16.04
> Codename: xenial
> 
> java version "1.8.0_101"
> Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
