### ISSUE TITLE
brat2tbf

### ISSUE THREAD

**Issue by Ani2016** [hunterhector/EvmEval#15]
I am having this error
kindly let me know how to run this code

Asad:EvmEval-master asad$ ./util/brat2tbf.py ajax.ann -t util/ajax.txt [-o OUT] 
usage: brat2tbf.py [-h] (-d DIR | -f FILE) [-t TOKEN_PATH] [-o OUT] [-oe EXT]
                   [-i EID] [-w] [-of OFFSET_FIELD]
                   [-te TOKEN_TABLE_EXTENSION] [-ae ANNOTATION_EXTENSION] [-b]
brat2tbf.py: error: one of the arguments -d/--dir -f/--file is required
Asad:EvmEval-master asad$ ./util/brat2tbf.py ajax.ann -t util [-o OUT] 
usage: brat2tbf.py [-h] (-d DIR | -f FILE) [-t TOKEN_PATH] [-o OUT] [-oe EXT]
                   [-i EID] [-w] [-of OFFSET_FIELD]
                   [-te TOKEN_TABLE_EXTENSION] [-ae ANNOTATION_EXTENSION] [-b]
brat2tbf.py: error: one of the arguments -d/--dir -f/--file is required

**Comment by hunterhector** [comment]
Hi，

As suggested by the message:

brat2tbf.py: error: one of the arguments -d/--dir -f/--file is required

if the input is one file, then use the "-f" option, the simplest command would be:

brat2tbf.py -f ajax.ann -t util/ajax.txt

**Comment by Ani2016** [comment]
![util dir 2017-06-04 at 1 50 29 am](https://cloud.githubusercontent.com/assets/29122269/26756984/7fa4993e-48c8-11e7-9379-9ab35c1a6fba.png)
Hello,

Thanks for your response 
but still i received an error

Asad:util asad$ ./brat2tbf.py -f ajax.ann -t util/ajax.txt
[ERROR] 2017-06-04 01:33:00,408 : Token directory does not exists (or is not a directory)

**Comment by hunterhector** [comment]
I don't think you really need a token file. The token file is used to convert the annotation to the token based format. 

If you really a token directory, you need to follow a specific format and file extension convention, which comes with previous TAC KBP corpus. In addition, the "-t" argument requires a directory, not a file, as the error message suggested. 

Simply leave out the "-t" option.
