### ISSUE TITLE
demo_score.sh and scorer_test.py are outdated

### ISSUE THREAD

**Issue by peter-makarov** [hunterhector/EvmEval#16]
Hi there!

#`demo_score.sh` is outdated. Running it produces the following output:

Evaluating system A, should be a perfect system

[INFO] 2017-09-06 15:55:35,544 : Evaluation output will be saved at data/scoring_demo/score_prefect.scores
[ERROR] 2017-09-06 15:55:35,544 : Cannot find gold standard file at data/scoring_demo/gold.tbf
Stored score report at data/scoring_demo/score_prefect.tmp

After the following changes to the script:

```shell
scorer=./scorer_v1.8.py

echo "Evaluating system A, should be a perfect system\n"
$scorer -g data/scoring_demo/token_based/gold.tbf -s data/scoring_demo/token_based/sample_system_A.tbf -d data/scoring_demo/A_out.tmp -t data/scoring_demo/token_based/tkn/ --eval_mode token -o data/scoring_demo/score_prefect.scores
echo "Stored score report at data/scoring_demo/score_prefect.tmp\n"
```

The first example works:

Evaluating system A, should be a perfect system

[INFO] 2017-09-06 15:59:19,851 : Evaluation output will be saved at data/scoring_demo/score_prefect.scores
[INFO] 2017-09-06 15:59:19,852 : Coreference mentions need to match mention_type before consideration
[INFO] 2017-09-06 15:59:19,852 : Evaluating Document example1
[INFO] 2017-09-06 15:59:19,852 : Evaluating Document example2
[INFO] 2017-09-06 15:59:19,857 : Evaluation Done.
Stored score report at data/scoring_demo/score_prefect.tmp

`scorer_test.py` is also outdated:

$ ./scorer_test.py 
Please see test_tmp/test.log for test logs.
Running mention tests
Running format error test cases.
Traceback (most recent call last):
  File "scorer_v1.8.py", line 1145, in <module>
    main()
  File "scorer_v1.8.py", line 266, in main
    diff_out):
  File "scorer_v1.8.py", line 974, in evaluate
    parse_result = parse_line(sl, invisible_ids)
  File "scorer_v1.8.py", line 688, in parse_line
    spans = parse_characters(fields[3])
  File "scorer_v1.8.py", line 646, in parse_characters
    span = list(map(int, span_strs.split(Config.span_joiner)))
ValueError: invalid literal for int() with base 10: 't3'

Best,
Peter

**Comment by hunterhector** [comment]
Hi,

Thanks for reporting this. I've updated the scoring_demo.sh file to use correct file paths and arguments. The "scorer_test" is supposed to run some difficult test case internally, which is slightly updated now, I am planning to remove it from the repository. The "scorer_demo" file should be enough to showcase the usage.

Best,
hector

**Comment by peter-makarov** [comment]
Looks good. Thanks a lot!
Peter
