### ISSUE TITLE
rich_ere to btf conversion

### ISSUE THREAD

**Issue by peter-makarov** [hunterhector/EvmEval#17]
Hi Hector,

I have a question. I see that there are two ways of converting from rich ere xmls to tbf:

* In one step, via `bin/rich_ere_to_tbf_converter.jar`
* Via brat format: first `bin/rich_ere_to_brat_converter.jar`,  then `util/brat2tbf.py`

Assuming that I use character mode, am I expected to always get the same output from both conversion methods?

Thanks and best,
Peter

**Comment by hunterhector** [comment]
Hi, Peter,

I would expect them to produce the same output, if not, then it sounds like a bug in one of the converters. 

Hector

**Comment by peter-makarov** [comment]
Thanks!
