### ISSUE TITLE
Subevent Evaluation

### ISSUE THREAD

**Issue by ghost** [hunterhector/EvmEval#18]
Hello, 
Thanks for providing this scorer. I am just wondering how to evaluate the subevents without the After relation. 
Thanks

**Comment by hunterhector** [comment]
At the moment both subscores for After and Subevent will be produced. So if you have a system without after links, you can still look at the subevent part only.

**Comment by ghost** [comment]
Thank you for your prompt reply. So what is the format to include the subevents. What I know is the format for "After" relation that should be something like this: 
@After E3, E4
@After E4, E5
@After E5, E6

In terms of Parent-Child relations, which one of these events should be the position of the parent event. Or is this even the right format for subevents relations? 

I really appreciate your time.

**Comment by hunterhector** [comment]
Oh, I just realize that the example files do not contain examples for the "Subevent" relation. 

The format is:

@Subevent E1,E2

Where E1 is the parent. Note the marker for "after" relation is @After, with capitalized "A"

**Comment by ghost** [comment]
Thank you so much.  To be sure: 
@Subevent	A1	E1,E2
@Subevent	A2	E1,E4

means that E2 is a subevent of E1 and E4 is a subevent of E1 as well, is that correct? 

Also (it might be a silly question ) do the lines of the event detection (types and subtypes) affect the score of the sequence?  I just want to evaluate the subevent structure where the events are already known.

**Comment by hunterhector** [comment]
Question 1: Correct.
Question 2: the detection affect the scores. Behind the scene, there is one step for event mention matching between gold standard and system. The scorer here implements several matching mechanisms, but the default matching mechanism requires both the spans and types (subtypes) to be correct. 

To evaluate on subevent structures only, the best way is to make sure the system event mention output is exactly the same as the gold standard.

**Comment by ghost** [comment]
Thank you so much.

**Comment by ghost** [comment]
I was able to evaluate the results but  got this result in one of the runs, to me it did not make any sense, so I am just wondering if this behavior expected 

=== Temporal Awareness Score ===
Evaluated considering implicit relations in recall as well
Temporal Score	F1	P	R
		     0.8427	       1.4354      	0.5964	
Overall Temporal Awareness Score (F1 score): 0.8427

thanks

**Comment by hunterhector** [comment]
So you wonder this might not make sense because the P is larger than 1? In fact, the output is scaled to 100, so the upper bound for F1 (including P and R) is 100 instead of 1.

This score might seem too low to you but I have seen systems produce something like that before, the task is just too difficult. We need to check the submission file to see if it is really that low or there is simply some formatting issue.
